from pathlib import Path
LINES = [
    "import type { Response } from \"express\";",
    "import type { ReportFormat, ReportRunResponse } from \"../types/report.types.js\";",
    "",
    "export interface DownloadOptions {",
    "  fileName?: string;",
    "}",
    "",
    "export interface DownloadFormatConfig {",
    "  mimeType: string;",
    "  extension: string;",
    "  serialize: (report: ReportRunResponse) => string | Buffer;",
    "}",
    "",
    "export class Download {",
    "  private readonly formats = new Map<string, DownloadFormatConfig>();",
    "",
    "  constructor() {",
    "    this.registerBuiltInFormats();",
    "  }",
    "",
    "  registerFormat(format: string, config: DownloadFormatConfig): this {",
    "    this.formats.set(format.toLowerCase(), config);",
    "    return this;",
    "  }",
    "",
    "  hasFormat(format: string): boolean {",
    "    return this.formats.has(format.toLowerCase());",
    "  }",
    "",
    "  send(res: Response, report: ReportRunResponse, options?: DownloadOptions): Response {",
    "    const config = this.getFormatConfig(report.format);",
    "    const body = config.serialize(report);",
    "    const fileName = this.buildFileName(report.format, options?.fileName, config.extension);",
    "    res.setHeader(\"Content-Type\", config.mimeType);",
    "    res.setHeader(\"Content-Disposition\", \"attachment; filename=\\\"\" + fileName + \"\\\"\");",
    "    return res.status(200).send(body);",
    "  }",
    "",
    "  private registerBuiltInFormats(): void {",
    "    this.registerFormat(\"csv\", {",
    "      mimeType: \"text/csv; charset=utf-8\",",
    "      extension: \"csv\",",
    "      serialize: (report) => {",
    "        if (report.content == null) {",
    "          throw new Error(\"CSV report has no content to download\");",
    "        }",
    "        return report.content;",
    "      },",
    "    });",
    "    this.registerFormat(\"json\", {",
    "      mimeType: \"application/json; charset=utf-8\",",
    "      extension: \"json\",",
    "      serialize: (report) =>",
    "        JSON.stringify({ meta: report.meta, rows: report.rows ?? [] }, null, 2),",
    "    });",
    "  }",
    "",
    "  private getFormatConfig(format: ReportFormat | string): DownloadFormatConfig {",
    "    const config = this.formats.get(String(format).toLowerCase());",
    "    if (!config) {",
    "      const supported = [...this.formats.keys()].join(\", \");",
    "      throw new Error(",
    "        \"Unsupported download format: \" + format + \". Supported formats: \" + supported",
    "      );",
    "    }",
    "    return config;",
    "  }",
    "",
    "  private buildFileName(_format: string, baseName: string | undefined, extension: string): string {",
    "    const defaultBase = \"report-\" + new Date().toISOString().slice(0, 10);",
    "    const safeBase = this.sanitizeFileName(baseName?.replace(/\\.[^.]+$/, \"\") ?? defaultBase);",
    "    return safeBase + \".\" + extension;",
    "  }",
    "",
    "  private sanitizeFileName(name: string): string {",
    "    return name.replace(/[^\\w.\\-]/g, \"_\") || \"report\";",
    "  }",
    "}",
    "",
    "export const reportDownload = new Download();",
]
INDEX = [
    "export { Download, reportDownload } from \"./download.js\";",
    "export type { DownloadFormatConfig, DownloadOptions } from \"./download.js\";",
]
root = Path("src/reports/download")
root.mkdir(parents=True, exist_ok=True)
(root / "download.ts").write_text("\n".join(LINES) + "\n", encoding="utf-8")
(root / "index.ts").write_text("\n".join(INDEX) + "\n", encoding="utf-8")
print("OK")