export enum Permission {
    // School
    CREATE_SCHOOL = "CREATE_SCHOOL",
    VIEW_SCHOOL = "VIEW_SCHOOL",
    EDIT_SCHOOL = "EDIT_SCHOOL",
    DELETE_SCHOOL = "DELETE_SCHOOL",
  
    // Branch
    CREATE_BRANCH = "CREATE_BRANCH",
    VIEW_BRANCH = "VIEW_BRANCH",
    EDIT_BRANCH = "EDIT_BRANCH",
    DELETE_BRANCH = "DELETE_BRANCH",
  
    // Class
    CREATE_CLASS = "CREATE_CLASS",
    VIEW_CLASS = "VIEW_CLASS",
    EDIT_CLASS = "EDIT_CLASS",
    DELETE_CLASS = "DELETE_CLASS",
  
    // Student
    CREATE_STUDENT = "CREATE_STUDENT",
    VIEW_STUDENT = "VIEW_STUDENT",
    EDIT_STUDENT = "EDIT_STUDENT",
    DELETE_STUDENT = "DELETE_STUDENT",
    BULK_UPLOAD_STUDENTS = "BULK_UPLOAD_STUDENTS",
  
    // Parent
    CREATE_PARENT = "CREATE_PARENT",
    VIEW_PARENT = "VIEW_PARENT",
    EDIT_PARENT = "EDIT_PARENT",
    DELETE_PARENT = "DELETE_PARENT",
  
    // Fees
    CREATE_FEE_DOC = "CREATE_FEE_DOC",
    VIEW_FEE_DOC = "VIEW_FEE_DOC",
    EDIT_FEE_DOC = "EDIT_FEE_DOC",
    DELETE_FEE_DOC = "DELETE_FEE_DOC",
    RECORD_FEE_TRANSACTION = "RECORD_FEE_TRANSACTION",
    VIEW_FEE_SUMMARY = "VIEW_FEE_SUMMARY",
  
    // Session
    CREATE_SESSION = "CREATE_SESSION",
    VIEW_SESSION = "VIEW_SESSION",
    EDIT_SESSION = "EDIT_SESSION",
    LOCK_SESSION = "LOCK_SESSION",
    PROMOTE_STUDENTS = "PROMOTE_STUDENTS",
  
    // Reports
    VIEW_REPORTS = "VIEW_REPORTS",
    EXPORT_REPORTS = "EXPORT_REPORTS",
  
    // Documents
    GENERATE_ID_CARD = "GENERATE_ID_CARD",
    GENERATE_TRANSFER_CERTIFICATE = "GENERATE_TRANSFER_CERTIFICATE",
  
    // Notifications
    SEND_NOTIFICATION = "SEND_NOTIFICATION",
    VIEW_NOTIFICATIONS = "VIEW_NOTIFICATIONS",
  }
  
  
  export type PermissionType = keyof typeof Permission;
  
  export interface PAYLOAD_TOKEN_TYPE {
    userId:string
  }

export enum OTP_TYPE {
  SIGNIN_OTP="SIGNIN_OTP",
  VERIFY_OTP="VERIFY_OTP"
}

