/*
  Warnings:

  - The values [CREATE_FEE_DOC,VIEW_FEE_DOC,RECORD_FEE_TRANSACTION,VIEW_FEE_SUMMARY] on the enum `Permission` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "public"."Permission_new" AS ENUM ('ALL', 'CREATE_SCHOOL', 'VIEW_SCHOOL', 'EDIT_SCHOOL', 'DELETE_SCHOOL', 'CREATE_BRANCH', 'VIEW_BRANCH', 'EDIT_BRANCH', 'DELETE_BRANCH', 'CREATE_CLASS', 'VIEW_CLASS', 'EDIT_CLASS', 'DELETE_CLASS', 'CREATE_CLASSNAME', 'VIEW_CLASSNAME', 'CREATE_STUDENT', 'VIEW_STUDENT', 'EDIT_STUDENT', 'DELETE_STUDENT', 'BULK_UPLOAD_STUDENTS', 'GET_BULK_UPLOAD_SHEET', 'CREATE_PARENT', 'VIEW_PARENT', 'EDIT_PARENT', 'DELETE_PARENT', 'CREATE_FEE_HEAD', 'VIEW_FEE_HEAD', 'EDIT_FEE_HEAD', 'DELETE_FEE_HEAD', 'CREATE_FEE_TEMPLATE', 'VIEW_FEE_TEMPLATE', 'EDIT_FEE_TEMPLATE', 'DELETE_FEE_TEMPLATE', 'GENERATE_FEE_DOCS', 'VIEW_FEE_DOCS', 'EDIT_FEE_DOC', 'DELETE_FEE_DOC', 'CREATE_FEE_PAYMENT', 'VIEW_FEE_PAYMENTS', 'EDIT_FEE_PAYMENT', 'DELETE_FEE_PAYMENT', 'CREATE_FEE_TRANSACTION', 'VIEW_FEE_TRANSACTIONS', 'VIEW_BRANCH_FEE_REPORT', 'CREATE_SESSION', 'VIEW_SESSION', 'EDIT_SESSION', 'DELETE_SESSION', 'LOCK_SESSION', 'PROMOTE_STUDENTS', 'VIEW_REPORTS', 'EXPORT_REPORTS', 'GENERATE_ID_CARD', 'GENERATE_TRANSFER_CERTIFICATE', 'UPLOAD_DOCUMENT', 'VIEW_DOCUMENT', 'DELETE_DOCUMENT', 'SEND_NOTIFICATION', 'VIEW_NOTIFICATIONS', 'DELETE_NOTIFICATION');
ALTER TABLE "public"."User" ALTER COLUMN "permissions" DROP DEFAULT;
ALTER TABLE "public"."User" ALTER COLUMN "permissions" TYPE "public"."Permission_new"[] USING ("permissions"::text::"public"."Permission_new"[]);
ALTER TYPE "public"."Permission" RENAME TO "Permission_old";
ALTER TYPE "public"."Permission_new" RENAME TO "Permission";
DROP TYPE "public"."Permission_old";
ALTER TABLE "public"."User" ALTER COLUMN "permissions" SET DEFAULT ARRAY[]::"public"."Permission"[];
COMMIT;
