import {
  FieldCategory,
  FieldResolverType,
  RegistryDataType,
  SourceModule,
} from "../../../generated/prisma/index.js";
import type { FieldDefinition } from "../types/field-definition.js";

export const academicFields: FieldDefinition[] = [
  {
    fieldKey: "session_name",
    label: "Session Name",
    sourceModule: SourceModule.ACADEMIC,
    sourceTable: "AcademicSession",
    sourceColumn: "name",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.STRING,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "academic_session",
    displayOrder: 10,
  },
  {
    fieldKey: "session_is_current",
    label: "Current Session",
    sourceModule: SourceModule.ACADEMIC,
    sourceTable: "AcademicSession",
    sourceColumn: "isCurrent",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.BOOLEAN,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "academic_session",
    displayOrder: 20,
  },
  {
    fieldKey: "session_is_locked",
    label: "Session Locked",
    sourceModule: SourceModule.ACADEMIC,
    sourceTable: "AcademicSession",
    sourceColumn: "isLocked",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.BOOLEAN,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "academic_session",
    displayOrder: 30,
  },
  {
    fieldKey: "class_label_name",
    label: "Class Label",
    sourceModule: SourceModule.ACADEMIC,
    sourceTable: "ClassLabel",
    sourceColumn: "name",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.STRING,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "class_structure",
    displayOrder: 40,
  },
  {
    fieldKey: "section_name",
    label: "Section Name",
    sourceModule: SourceModule.ACADEMIC,
    sourceTable: "Section",
    sourceColumn: "name",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.STRING,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "class_structure",
    displayOrder: 50,
  },
  {
    fieldKey: "subject_name",
    label: "Subject Name",
    sourceModule: SourceModule.ACADEMIC,
    sourceTable: "Subject",
    sourceColumn: "name",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.STRING,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "class_structure",
    displayOrder: 60,
  },
  {
    fieldKey: "school_day_date",
    label: "School Day Date",
    sourceModule: SourceModule.ACADEMIC,
    sourceTable: "SchoolDay",
    sourceColumn: "date",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.DATE,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "school_calendar",
    displayOrder: 70,
  },
  {
    fieldKey: "school_day_type",
    label: "School Day Type",
    sourceModule: SourceModule.ACADEMIC,
    sourceTable: "SchoolDay",
    sourceColumn: "type",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.ENUM,
    enumName: "SchoolDayType",
    resolverType: FieldResolverType.COLUMN,
    groupKey: "school_calendar",
    displayOrder: 80,
  },
];
