import {
  FieldCategory,
  FieldResolverType,
  RegistryDataType,
  SourceModule,
} from "../../../generated/prisma/index.js";
import type { FieldDefinition } from "../types/field-definition.js";

export const attendanceFields: FieldDefinition[] = [
  {
    fieldKey: "attendance_status",
    label: "Attendance Status",
    sourceModule: SourceModule.ATTENDANCE,
    sourceTable: "Attendance",
    sourceColumn: "status",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.ENUM,
    enumName: "AttendanceStatus",
    resolverType: FieldResolverType.COLUMN,
    groupKey: "attendance",
    displayOrder: 10,
  },
  {
    fieldKey: "attendance_type",
    label: "Attendance Type",
    sourceModule: SourceModule.ATTENDANCE,
    sourceTable: "Attendance",
    sourceColumn: "type",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.ENUM,
    enumName: "AttendanceType",
    resolverType: FieldResolverType.COLUMN,
    groupKey: "attendance",
    displayOrder: 20,
  },
  {
    fieldKey: "attendance_method",
    label: "Attendance Method",
    sourceModule: SourceModule.ATTENDANCE,
    sourceTable: "Attendance",
    sourceColumn: "method",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.ENUM,
    enumName: "AttendanceMethod",
    resolverType: FieldResolverType.COLUMN,
    groupKey: "attendance",
    displayOrder: 30,
  },
  {
    fieldKey: "attendance_marked_at",
    label: "Marked At",
    sourceModule: SourceModule.ATTENDANCE,
    sourceTable: "Attendance",
    sourceColumn: "markedAt",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.DATETIME,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "attendance",
    displayOrder: 40,
  },
  {
    fieldKey: "lecture_status",
    label: "Lecture Status",
    sourceModule: SourceModule.ATTENDANCE,
    sourceTable: "Lecture",
    sourceColumn: "status",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.ENUM,
    enumName: "LectureStatus",
    resolverType: FieldResolverType.COLUMN,
    groupKey: "lecture",
    displayOrder: 50,
  },
  {
    fieldKey: "faculty_attendance_status",
    label: "Teacher Attendance Status",
    sourceModule: SourceModule.ATTENDANCE,
    sourceTable: "SchoolFacultyAttendance",
    sourceColumn: "status",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.ENUM,
    enumName: "AttendanceStatus",
    resolverType: FieldResolverType.COLUMN,
    groupKey: "faculty_attendance",
    displayOrder: 60,
  },
];
