import {
  FieldCategory,
  FieldResolverType,
  RegistryDataType,
  SourceModule,
} from "../../../generated/prisma/index.js";
import type { FieldDefinition } from "../types/field-definition.js";

export const computedFields: FieldDefinition[] = [
  {
    fieldKey: "attendance_percentage",
    label: "Attendance %",
    description: "Percentage of present days over working school days for the enrollment",
    sourceModule: SourceModule.ATTENDANCE,
    sourceTable: "Attendance",
    fieldCategory: FieldCategory.COMPUTED,
    dataType: RegistryDataType.PERCENTAGE,
    resolverType: FieldResolverType.AGGREGATE,
    resolverConfig: {
      provider: "attendancePercentage",
      numerator: { status: "PRESENT" },
      denominator: { workingDaysOnly: true },
      scope: { via: "Enrollment", foreignKey: "enrollmentId" },
    },
    isSortable: true,
    isFilterable: true,
    groupKey: "attendance_summary",
    displayOrder: 10,
    schemaVersion: 1,
  },
  {
    fieldKey: "pending_fees",
    label: "Pending Fees",
    description: "Sum of unpaid fee document amounts for the enrollment",
    sourceModule: SourceModule.FEE,
    sourceTable: "FeeDoc",
    fieldCategory: FieldCategory.COMPUTED,
    dataType: RegistryDataType.MONEY,
    resolverType: FieldResolverType.AGGREGATE,
    resolverConfig: {
      provider: "pendingFees",
      where: { status: ["PENDING", "PARTIAL"] },
      scope: { via: "Enrollment", foreignKey: "enrollmentId" },
    },
    isSortable: true,
    isFilterable: true,
    groupKey: "fee_summary",
    displayOrder: 20,
    schemaVersion: 1,
  },
  {
    fieldKey: "total_fees_paid",
    label: "Total Fees Paid",
    description: "Sum of all fee transaction amounts for the enrollment",
    sourceModule: SourceModule.FEE,
    sourceTable: "FeeTransaction",
    fieldCategory: FieldCategory.COMPUTED,
    dataType: RegistryDataType.MONEY,
    resolverType: FieldResolverType.AGGREGATE,
    resolverConfig: {
      provider: "sumFeeTransactions",
      column: "amountPaid",
      scope: { via: "Enrollment", foreignKey: "enrollmentId" },
    },
    isSortable: true,
    isFilterable: true,
    groupKey: "fee_summary",
    displayOrder: 30,
    schemaVersion: 1,
  },
  {
    fieldKey: "exam_average",
    label: "Exam Average",
    description: "Average exam score (placeholder until exam module is implemented)",
    sourceModule: SourceModule.EXAM,
    sourceTable: "Student",
    fieldCategory: FieldCategory.COMPUTED,
    dataType: RegistryDataType.NUMBER,
    resolverType: FieldResolverType.EXPRESSION,
    resolverConfig: {
      provider: "examAverage",
      status: "NOT_IMPLEMENTED",
    },
    isFilterable: false,
    isSortable: false,
    groupKey: "exam_summary",
    displayOrder: 40,
    schemaVersion: 1,
  },
];
