import {
  FieldCategory,
  FieldResolverType,
  RegistryDataType,
  SourceModule,
} from "../../../generated/prisma/index.js";
import type { FieldDefinition } from "../types/field-definition.js";

export const studentFields: FieldDefinition[] = [
  {
    fieldKey: "student_name",
    label: "Student Name",
    sourceModule: SourceModule.STUDENT,
    sourceTable: "Student",
    sourceColumn: "name",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.STRING,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "student_identity",
    displayOrder: 10,
  },
  {
    fieldKey: "student_admission_no",
    label: "Admission No",
    sourceModule: SourceModule.STUDENT,
    sourceTable: "Student",
    sourceColumn: "admissionNo",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.STRING,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "student_identity",
    displayOrder: 20,
  },
  {
    fieldKey: "student_id_number",
    label: "Student ID",
    sourceModule: SourceModule.STUDENT,
    sourceTable: "Student",
    sourceColumn: "studentId",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.STRING,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "student_identity",
    displayOrder: 30,
  },
  {
    fieldKey: "student_email",
    label: "Student Email",
    sourceModule: SourceModule.STUDENT,
    sourceTable: "Student",
    sourceColumn: "studentEmail",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.STRING,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "student_contact",
    displayOrder: 40,
  },
  {
    fieldKey: "student_mobile",
    label: "Student Mobile",
    sourceModule: SourceModule.STUDENT,
    sourceTable: "Student",
    sourceColumn: "studentMobile",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.STRING,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "student_contact",
    displayOrder: 50,
  },
  {
    fieldKey: "student_gender",
    label: "Gender",
    sourceModule: SourceModule.STUDENT,
    sourceTable: "Student",
    sourceColumn: "gender",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.STRING,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "student_identity",
    displayOrder: 60,
  },
  {
    fieldKey: "student_dob",
    label: "Date of Birth",
    sourceModule: SourceModule.STUDENT,
    sourceTable: "Student",
    sourceColumn: "dob",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.DATE,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "student_identity",
    displayOrder: 70,
  },
  {
    fieldKey: "student_aadhaar",
    label: "Aadhaar",
    sourceModule: SourceModule.STUDENT,
    sourceTable: "Student",
    sourceColumn: "aadhaar",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.STRING,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "student_documents",
    displayOrder: 80,
    isExportable: false,
  },
  {
    fieldKey: "student_permanent_address",
    label: "Permanent Address",
    sourceModule: SourceModule.STUDENT,
    sourceTable: "Student",
    sourceColumn: "permanentAddress",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.STRING,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "student_address",
    displayOrder: 90,
  },
  {
    fieldKey: "student_special_child",
    label: "Special Child",
    sourceModule: SourceModule.STUDENT,
    sourceTable: "Student",
    sourceColumn: "specialChild",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.BOOLEAN,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "student_identity",
    displayOrder: 100,
  },
  {
    fieldKey: "father_name",
    label: "Father Name",
    sourceModule: SourceModule.STUDENT,
    sourceTable: "Student",
    sourceColumn: "fatherName",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.STRING,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "parent_info",
    displayOrder: 110,
  },
  {
    fieldKey: "father_mobile",
    label: "Father Mobile",
    sourceModule: SourceModule.STUDENT,
    sourceTable: "Student",
    sourceColumn: "fatherMobile",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.STRING,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "parent_info",
    displayOrder: 120,
  },
  {
    fieldKey: "father_email",
    label: "Father Email",
    sourceModule: SourceModule.STUDENT,
    sourceTable: "Student",
    sourceColumn: "fatherEmail",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.STRING,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "parent_info",
    displayOrder: 130,
  },
  {
    fieldKey: "mother_name",
    label: "Mother Name",
    sourceModule: SourceModule.STUDENT,
    sourceTable: "Student",
    sourceColumn: "motherName",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.STRING,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "parent_info",
    displayOrder: 140,
  },
  {
    fieldKey: "mother_mobile",
    label: "Mother Mobile",
    sourceModule: SourceModule.STUDENT,
    sourceTable: "Student",
    sourceColumn: "motherMobile",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.STRING,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "parent_info",
    displayOrder: 150,
  },
  {
    fieldKey: "mother_email",
    label: "Mother Email",
    sourceModule: SourceModule.STUDENT,
    sourceTable: "Student",
    sourceColumn: "motherEmail",
    fieldCategory: FieldCategory.RAW,
    dataType: RegistryDataType.STRING,
    resolverType: FieldResolverType.COLUMN,
    groupKey: "parent_info",
    displayOrder: 160,
  },
];
